/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clinicemail.sendmail;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author farah
 */
public class AppointmentAssistant extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentAssistant
     */
    public AppointmentAssistant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        appid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(72, 87, 164));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(72, 87, 164));
        jLabel1.setText("WELCOME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, -1));

        jButton3.setBackground(new java.awt.Color(242, 242, 242));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(72, 87, 164));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 191209 (1).gif"))); // NOI18N
        jButton3.setText("Appointment ");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 320, 110));

        jButton4.setBackground(new java.awt.Color(242, 242, 242));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(72, 87, 164));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 191921.gif"))); // NOI18N
        jButton4.setText("  Treatment");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 320, 110));

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(72, 87, 164));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-04 185610.gif"))); // NOI18N
        jButton1.setText("Cost");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 320, 110));

        jButton2.setBackground(new java.awt.Color(242, 242, 242));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(72, 87, 164));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 191732 (1).gif"))); // NOI18N
        jButton2.setText("  Patient ");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 320, 110));

        jButton9.setBackground(new java.awt.Color(242, 242, 242));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(72, 87, 164));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 192236 (1).gif"))); // NOI18N
        jButton9.setText(" Dintests");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 320, 120));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(72, 87, 164));
        jLabel3.setText("Appoitment id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, 37));

        pname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pname.setForeground(new java.awt.Color(72, 87, 164));
        pname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 270, 37));

        jButton5.setBackground(new java.awt.Color(242, 242, 242));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(72, 87, 164));
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 280, 190, 60));

        jButton7.setBackground(new java.awt.Color(242, 242, 242));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(72, 87, 164));
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 590, 190, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(72, 87, 164));
        jLabel4.setText("Assistant");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 160, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Appointment_id", "patien_id", "Appointment_time", "patient_name", "Appointment_date"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 770, 330));

        jButton10.setBackground(new java.awt.Color(242, 242, 242));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(72, 87, 164));
        jButton10.setText("Show");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 350, 190, 60));

        jButton6.setBackground(new java.awt.Color(242, 242, 242));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(72, 87, 164));
        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 430, 190, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(72, 87, 164));
        jLabel5.setText("patient id");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 100, -1, 37));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(72, 87, 164));
        jLabel8.setText("Time");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(72, 87, 164));
        jLabel9.setText("Appointment");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, 37));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(72, 87, 164));
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 270, 37));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(72, 87, 164));
        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 270, 37));

        jDateChooser1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        jDateChooser1.setForeground(new java.awt.Color(72, 87, 164));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 180, 270, 40));

        jButton8.setBackground(new java.awt.Color(242, 242, 242));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(72, 87, 164));
        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 510, 190, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(72, 87, 164));
        jLabel10.setText("Appointment ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, -1, 37));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(72, 87, 164));
        jLabel11.setText("Date");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 200, -1, 40));

        jButton11.setBackground(new java.awt.Color(242, 242, 242));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-01-01 011758_1.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 770, 110, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(72, 87, 164));
        jLabel6.setText("Patient name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, 37));

        appid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        appid.setForeground(new java.awt.Color(72, 87, 164));
        appid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        appid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appidActionPerformed(evt);
            }
        });
        getContentPane().add(appid, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 270, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1920x1080-white-solid-color-background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          AppointmentAssistant appointment = new AppointmentAssistant();
        appointment.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         TreatmentAssistant treatment = new TreatmentAssistant();
        treatment.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      CostDetails CostDetails1 = new CostDetails();
        CostDetails1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       assistantP patient = new assistantP();
        patient.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         Dentists diagnosis = new Dentists();
        diagnosis.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String pnameInput = pname.getText().trim();  

if (pnameInput.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter a Patient Name to search.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
model.setRowCount(0);  

String url = "jdbc:postgresql://localhost:5432/postgres";
String user = "dentalclinic";
String password = "12345";

String sql = "SELECT * FROM public.appointments WHERE pname = ?";  

try (Connection conn = DriverManager.getConnection(url, user, password);
     PreparedStatement stmt = conn.prepareStatement(sql)) {

    stmt.setString(1, pnameInput);  

    try (ResultSet rs = stmt.executeQuery()) {
        boolean found = false;
        while (rs.next()) {  
            int aid = rs.getInt("appointment_id");
            int pid = rs.getInt("pid"); 
            String pname = rs.getString("pname");  
            String ptime = rs.getString("atime");  
            Date adate = rs.getDate("adate");

            String formattedDate = adate != null ? adate.toString() : ""; 

            model.addRow(new Object[]{aid, pid, pname, ptime, formattedDate}); // Adding in the correct order
            found = true;
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, "No appointment found for Patient Name: " + pnameInput, "No Results", JOptionPane.INFORMATION_MESSAGE);
        }
    }
} catch (SQLException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error retrieving data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
String appointmentIdInput = appid.getText().trim();

if (appointmentIdInput.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter an Appointment ID to delete the appointment.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

int appointmentId;
try {
    appointmentId = Integer.parseInt(appointmentIdInput);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Appointment ID must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

String url = "jdbc:postgresql://localhost:5432/postgres";
String user = "dentalclinic";
String password = "12345";

String query = "DELETE FROM public.appointments WHERE appointment_id = ?";

try (Connection con = DriverManager.getConnection(url, user, password);
     PreparedStatement pst = con.prepareStatement(query)) {
    
    pst.setInt(1, appointmentId);

    int rowsDeleted = pst.executeUpdate();

    if (rowsDeleted > 0) {
        JOptionPane.showMessageDialog(this, "Appointment deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        appid.setText("");
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();  
        model.setRowCount(0);
    } else {
        JOptionPane.showMessageDialog(this, "No appointment found with the given Appointment ID.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }

} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error while deleting appointment: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
model.setRowCount(0);

String url = "jdbc:postgresql://localhost:5432/postgres";
String user = "dentalclinic";
String password = "12345";

String sql = "SELECT * FROM public.appointments"; 

try (Connection conn = DriverManager.getConnection(url, user, password);
     PreparedStatement stmt = conn.prepareStatement(sql);
     ResultSet rs = stmt.executeQuery()) {

    
    while (rs.next()) {
        int aid=rs.getInt("appointment_id");
        int pid = rs.getInt("pid"); 
        String pname = rs.getString("pname");  
        String ptime = rs.getString("atime");  
        Date adate = rs.getDate("adate");  

      
        String formattedDate = adate != null ? adate.toString() : ""; 

     
        model.addRow(new Object[]{aid,pid, pname, ptime, formattedDate});
    }
} catch (SQLException ex) {
    ex.printStackTrace(); 
    JOptionPane.showMessageDialog(this, "Error retrieving data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

          

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// Retrieve user inputs
String pidInput = jTextField3.getText().trim();      
String patientName = pname.getText().trim();    
String atime = jTextField7.getText().trim();          
java.util.Date adate = jDateChooser1.getDate();      


if (pidInput.isEmpty() || patientName.isEmpty() || atime.isEmpty() || adate == null) {
    JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

int pid;
try {
    pid = Integer.parseInt(pidInput); 
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Patient ID must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}


java.sql.Time sqlTime;
try {
    sqlTime = java.sql.Time.valueOf(atime); 
} catch (IllegalArgumentException e) {
    JOptionPane.showMessageDialog(this, "Appointment time must be in the format HH:MM:SS.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}


java.sql.Date sqlDate = new java.sql.Date(adate.getTime());


String url = "jdbc:postgresql://localhost:5432/postgres";
String user = "dentalclinic";
String password = "12345";


String checkPatientQuery = "SELECT 1 FROM public.patients WHERE pid = ?";
String insertPatientQuery = "INSERT INTO public.patients (pid, pname) VALUES (?, ?)";
String insertAppointmentQuery = "INSERT INTO public.appointments (pid, pname, atime, adate) VALUES (?, ?, ?, ?)";

try (Connection con = DriverManager.getConnection(url, user, password);
     PreparedStatement checkStmt = con.prepareStatement(checkPatientQuery);
     PreparedStatement insertPatientStmt = con.prepareStatement(insertPatientQuery);
     PreparedStatement insertAppointmentStmt = con.prepareStatement(insertAppointmentQuery)) {

   
    checkStmt.setInt(1, pid);
    ResultSet rs = checkStmt.executeQuery();

    if (!rs.next()) {
        
        insertPatientStmt.setInt(1, pid);
        insertPatientStmt.setString(2, patientName); 
        insertPatientStmt.executeUpdate();
    }

   
    insertAppointmentStmt.setInt(1, pid);
    insertAppointmentStmt.setString(2, patientName);
    insertAppointmentStmt.setTime(3, sqlTime);
    insertAppointmentStmt.setDate(4, sqlDate);
    int rowsInserted = insertAppointmentStmt.executeUpdate();

    if (rowsInserted > 0) {
        JOptionPane.showMessageDialog(this, "Appointment added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Failed to add the appointment.", "Error", JOptionPane.ERROR_MESSAGE);
    }

} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Unexpected error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}





    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
String appointmentIdInput = appid.getText().trim(); 
String atime = jTextField7.getText().trim();          
java.util.Date adate = jDateChooser1.getDate();       

if (appointmentIdInput.isEmpty() || (atime.isEmpty() && adate == null)) {
    JOptionPane.showMessageDialog(null, "Please fill in all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

int appointmentId;
try {
    appointmentId = Integer.parseInt(appointmentIdInput); 
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(null, "Appointment ID must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

java.sql.Time sqlTime = null;
if (!atime.isEmpty()) {
    try {
        sqlTime = java.sql.Time.valueOf(atime); 
    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(null, "Appointment time must be in the format HH:MM:SS.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
}

java.sql.Date sqlDate = null;
if (adate != null) {
    sqlDate = new java.sql.Date(adate.getTime());
}

String url = "jdbc:postgresql://localhost:5432/postgres";
String user = "dentalclinic";
String password = "12345";

String updateAppointmentQuery;
if (sqlTime != null && sqlDate == null) {
    updateAppointmentQuery = "UPDATE public.appointments SET atime = ? WHERE appointment_id = ?";
} else if (sqlDate != null && sqlTime == null) {
    updateAppointmentQuery = "UPDATE public.appointments SET adate = ? WHERE appointment_id = ?";
} else {
    JOptionPane.showMessageDialog(null, "Specify either a new time or a new date, not both.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

try (Connection con = DriverManager.getConnection(url, user, password);
     PreparedStatement updateStmt = con.prepareStatement(updateAppointmentQuery)) {

    int paramIndex = 1;
    if (sqlTime != null) {
        updateStmt.setTime(paramIndex++, sqlTime);
    } else if (sqlDate != null) {
        updateStmt.setDate(paramIndex++, sqlDate);
    }
    updateStmt.setInt(paramIndex, appointmentId);

    int rowsUpdated = updateStmt.executeUpdate();

    if (rowsUpdated > 0) {
        JOptionPane.showMessageDialog(null, "Appointment updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "No appointment found for the given Appointment ID.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }

} catch (SQLException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Unexpected error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}



    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      
        wlecomepage lb=new wlecomepage();
        lb.show();
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void appidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentAssistant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField appid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField pname;
    // End of variables declaration//GEN-END:variables
}
