/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clinicemail.sendmail;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author farah
 */
public class Dentists extends javax.swing.JFrame {

    /**
     * Creates new form Dentists
     */
    public Dentists() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        list = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(72, 87, 164));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(72, 87, 164));
        jLabel1.setText("WELCOME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, -1));

        jButton3.setBackground(new java.awt.Color(242, 242, 242));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(72, 87, 164));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 191209 (1).gif"))); // NOI18N
        jButton3.setText("Appointment ");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 320, 110));

        jButton4.setBackground(new java.awt.Color(242, 242, 242));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(72, 87, 164));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 191921.gif"))); // NOI18N
        jButton4.setText("  Treatment");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 320, 110));

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(72, 87, 164));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-04 185610.gif"))); // NOI18N
        jButton1.setText("Cost");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 320, 110));

        jButton2.setBackground(new java.awt.Color(242, 242, 242));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(72, 87, 164));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 191732 (1).gif"))); // NOI18N
        jButton2.setText("  Patient ");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 320, 110));

        jButton9.setBackground(new java.awt.Color(242, 242, 242));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(72, 87, 164));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 192236 (1).gif"))); // NOI18N
        jButton9.setText(" Dintests");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 320, 120));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(72, 87, 164));
        jLabel3.setText("Staff_id ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, 37));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(72, 87, 164));
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 270, 37));

        jButton5.setBackground(new java.awt.Color(242, 242, 242));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(72, 87, 164));
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 280, 190, 60));

        jButton7.setBackground(new java.awt.Color(242, 242, 242));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(72, 87, 164));
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 590, 190, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(72, 87, 164));
        jLabel4.setText("Assistant");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 150, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "staff_id", "staff_name", "role", "phone number", "email", "hire_date", "specialty"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 770, 330));

        jButton10.setBackground(new java.awt.Color(242, 242, 242));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(72, 87, 164));
        jButton10.setText("Show");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 350, 190, 60));

        jButton6.setBackground(new java.awt.Color(242, 242, 242));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(72, 87, 164));
        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 430, 190, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(72, 87, 164));
        jLabel5.setText("Specialty");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, 37));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(72, 87, 164));
        jLabel6.setText("phone");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, -1, 37));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(72, 87, 164));
        jLabel7.setText("Staff email ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 120, -1, 37));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(72, 87, 164));
        jLabel8.setText("Hire date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 180, -1, 37));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(72, 87, 164));
        jLabel9.setText("Staff_name ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, 37));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(72, 87, 164));
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 270, 37));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(72, 87, 164));
        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 120, 270, 37));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(72, 87, 164));
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 50, 270, 37));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(72, 87, 164));
        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 270, 37));

        jDateChooser1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        jDateChooser1.setForeground(new java.awt.Color(72, 87, 164));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 180, 270, 40));

        jButton8.setBackground(new java.awt.Color(242, 242, 242));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(72, 87, 164));
        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 510, 190, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(72, 87, 164));
        jLabel10.setText("Role");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, 37));

        jButton11.setBackground(new java.awt.Color(242, 242, 242));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-01-01 011758_1.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 770, 110, 80));

        list.setBackground(new java.awt.Color(242, 242, 242));
        list.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        list.setForeground(new java.awt.Color(72, 87, 164));
        list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dentist", "Assistant" }));
        list.setBorder(null);
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });
        getContentPane().add(list, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 270, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1920x1080-white-solid-color-background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1550, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          AppointmentAssistant appointment = new AppointmentAssistant();
        appointment.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         TreatmentAssistant treatment = new TreatmentAssistant();
        treatment.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CostDetails CostDetails1 = new CostDetails();
        CostDetails1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       assistantP patient = new assistantP();
        patient.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
          Dentists diagnosis = new Dentists();
        diagnosis.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

String sid = jTextField2.getText().trim(); 
String sName = jTextField7.getText().trim();

if (sid.isEmpty() || sName.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all fields to search.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

String url = "jdbc:postgresql://localhost:5432/postgres";
String user = "dentalclinic";
String password = "12345";


String query = "SELECT * FROM public.staff WHERE staff_id = ? AND name = ?";

try (
   
    Connection con = DriverManager.getConnection(url, user, password);
    
    PreparedStatement pst = con.prepareStatement(query)
) {
    
    pst.setInt(1, Integer.parseInt(sid)); 
    pst.setString(2, sName); 

    
    ResultSet rs = pst.executeQuery();

    
    if (rs.next()) {
        
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel(); 

        
        model.setRowCount(0);

        
        int columnCount = rs.getMetaData().getColumnCount();

        
        do {
            
            Object[] row = new Object[columnCount];

           
            for (int i = 1; i <= columnCount; i++) {
                row[i - 1] = rs.getObject(i);  
            }

            model.addRow(row); 
        } while (rs.next());

       
    } else {
        JOptionPane.showMessageDialog(this, "No record found matching the search criteria.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }

} catch (SQLException e) {
   
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error while searching: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
   
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    String sid = jTextField2.getText().trim();  

   
    if (sid.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a Patient ID to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int sId = -1;
    try {
       
        sId = Integer.parseInt(sid);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Patient ID must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

  
    String url = "jdbc:postgresql://localhost:5432/postgres";
    String user = "dentalclinic";
    String password = "12345";

  
    String query = "DELETE FROM public.staff WHERE staff_id = ?";

    try (
      
        Connection con = DriverManager.getConnection(url, user, password);
      
        PreparedStatement pst = con.prepareStatement(query)
    ) {
       
        pst.setInt(1, sId);

     
        int rowsDeleted = pst.executeUpdate();

      
        if (rowsDeleted > 0) {
          

           
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();  
            model.setRowCount(0);  

         
        } else {
            JOptionPane.showMessageDialog(this, "No patient found with the given ID.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (SQLException e) {
        
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error while deleting patient: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
    
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    
}
    
 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        String url = "jdbc:postgresql://localhost:5432/postgres";
        String user = "dentalclinic";
        String password ="12345" ;

        String sql = "SELECT * FROM public.staff";

        try (Connection conn = DriverManager.getConnection(url, user, password);
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                int sid = rs.getInt("staff_id");
                String sname = rs.getString("name");
                String rule = rs.getString("role");
                String phone = rs.getString("phone");
                String semail = rs.getString("email");
                Date hiredate = rs.getDate("hire_date");
                String specialty = rs.getString("specialty");

                model.addRow(new Object[]{sid, sname, rule,phone,semail,hiredate,specialty});

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
String sid = jTextField2.getText().trim(); 
String sname = jTextField7.getText().trim(); 
String role = list.getSelectedItem().toString().trim();
String phone = jTextField4.getText().trim(); 
String email = jTextField5.getText().trim(); 
java.util.Date hiredate = jDateChooser1.getDate(); 
String specialty = jTextField3.getText().trim(); 


if (sid.isEmpty() || sname.isEmpty() || role.isEmpty() || phone.isEmpty() || email.isEmpty() || hiredate == null || specialty.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all fields before adding.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

if (!phone.matches("\\d{10,15}")) { 
    JOptionPane.showMessageDialog(this, "Invalid phone number. Ensure it is numeric and between 10-15 digits.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

if ("Dentist".equalsIgnoreCase(role)) {
    if (specialty.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Specialty is required for a Dentist.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
} else {
    specialty = null; 
}

java.sql.Date sqlhiredate = new java.sql.Date(hiredate.getTime());


int staffId;
try {
    staffId = Integer.parseInt(sid);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Staff ID must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}


String url = "jdbc:postgresql://localhost:5432/postgres";
String user = "dentalclinic";
String password = "12345";


String query = "INSERT INTO public.staff (staff_id, name, role, phone, email, hire_date, specialty) VALUES (?, ?, ?, ?, ?, ?, ?)";

try (
    Connection con = DriverManager.getConnection(url, user, password);
    PreparedStatement pst = con.prepareStatement(query)
) {
  
    pst.setInt(1, staffId);
    pst.setString(2, sname);
    pst.setString(3, role);
    pst.setString(4, phone);
    pst.setString(5, email);
    pst.setDate(6, sqlhiredate);
    pst.setString(7, specialty);

    
    int rowsInserted = pst.executeUpdate();

    if (rowsInserted > 0) {
        JOptionPane.showMessageDialog(this, "Staff added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

       
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel(); 
        model.setRowCount(0); 
      
    } else {
        JOptionPane.showMessageDialog(this, "Error adding the staff.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }
} catch (SQLException e) {
   
    e.printStackTrace();
    if (e.getSQLState().equals("23514")) { 
        JOptionPane.showMessageDialog(this, "Input data violates database constraints: " + e.getMessage(), "Constraint Error", JOptionPane.ERROR_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Database error occurred: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
} catch (Exception e) {
  
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
  String sid = jTextField2.getText().trim(); 
    String sname = jTextField7.getText().trim();
String role = list.getSelectedItem().toString().trim();
    String phone = jTextField4.getText().trim(); 
    String email = jTextField5.getText().trim(); 
    java.util.Date hiredate = jDateChooser1.getDate(); 
    String specialty = jTextField3.getText().trim(); 

    
    if (sid.isEmpty() || sname.isEmpty() || role.isEmpty() || phone.isEmpty() || email.isEmpty() || hiredate == null || specialty.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields before updating.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

  

   
    if ("Dentist".equalsIgnoreCase(role)) {
        if (specialty.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Specialty is required for a Dentist.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } else {
        specialty = null; 
    }

   
    java.sql.Date sqlhiredate = new java.sql.Date(hiredate.getTime());

   
    int staffId;
    try {
        staffId = Integer.parseInt(sid);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Staff ID must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

   
    String url = "jdbc:postgresql://localhost:5432/postgres";
    String user = "dentalclinic";
    String password = "12345";

    
    String query = "UPDATE public.staff SET name = ?, role = ?, phone = ?, email = ?, hire_date = ?, specialty = ? WHERE staff_id = ? AND name = ?";

    try (
        Connection con = DriverManager.getConnection(url, user, password);
        PreparedStatement pst = con.prepareStatement(query)
    ) {
      
        pst.setString(1, sname);      
        pst.setString(2, role);       
        pst.setString(3, phone);      
        pst.setString(4, email);      
        pst.setDate(5, sqlhiredate);  
        pst.setString(6, specialty);  
        pst.setInt(7, staffId);       
        pst.setString(8, sname);     

       
        int rowsUpdated = pst.executeUpdate();

        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(this, "Staff updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

            
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0); 
          
        } else {
            JOptionPane.showMessageDialog(this, "No staff found with the given ID and name.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (SQLException e) {
        // Log and display database errors
        e.printStackTrace();
        if (e.getSQLState().equals("23514")) {
            JOptionPane.showMessageDialog(this, "Input data violates database constraints: " + e.getMessage(), "Constraint Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Database error occurred: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
     
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        wlecomepage lb=new wlecomepage();
        lb.show();
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dentists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dentists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dentists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dentists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dentists().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JComboBox<String> list;
    // End of variables declaration//GEN-END:variables
}
