/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clinicemail.sendmail;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author farah
 */
public class dianosis1 extends javax.swing.JFrame {

    /**
     * Creates new form dianosis1
     */
    public dianosis1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(72, 87, 164));
        jLabel2.setText("Diagnosis_id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, 148, 34));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 220, 34));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(72, 87, 164));
        jLabel3.setText("Petient_name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 154, 34));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 120, 240, 34));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(72, 87, 164));
        jLabel4.setText("Diagnosis_type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 190, 34));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 220, 34));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Diagnosis_id", "Patient_name", "Diagnosis_type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 910, 500));

        jButton5.setBackground(new java.awt.Color(242, 242, 242));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(72, 87, 164));
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 310, 220, 40));

        jButton6.setBackground(new java.awt.Color(242, 242, 242));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(72, 87, 164));
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 360, 220, 40));

        jButton7.setBackground(new java.awt.Color(242, 242, 242));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(72, 87, 164));
        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 410, 220, 40));

        jButton8.setBackground(new java.awt.Color(242, 242, 242));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(72, 87, 164));
        jButton8.setText("Show");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 730, 190, 60));

        jButton10.setBackground(new java.awt.Color(242, 242, 242));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(72, 87, 164));
        jButton10.setText("Delete");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 460, 220, 39));

        jButton11.setBackground(new java.awt.Color(242, 242, 242));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(72, 87, 164));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 191732 (1).gif"))); // NOI18N
        jButton11.setText("Patient ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 310, 120));

        jButton12.setBackground(new java.awt.Color(242, 242, 242));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(72, 87, 164));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 191921.gif"))); // NOI18N
        jButton12.setText("Treatment");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 310, 120));

        jButton13.setBackground(new java.awt.Color(242, 242, 242));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(72, 87, 164));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 191209.gif"))); // NOI18N
        jButton13.setText(" Appointment ");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 310, 120));

        jButton14.setBackground(new java.awt.Color(242, 242, 242));
        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(72, 87, 164));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-04 185610.gif"))); // NOI18N
        jButton14.setText("medication");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 310, 120));

        jButton15.setBackground(new java.awt.Color(242, 242, 242));
        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(72, 87, 164));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 192236 (1).gif"))); // NOI18N
        jButton15.setText("Diagnosis");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 310, 120));

        jLabel6.setBackground(new java.awt.Color(72, 87, 164));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(72, 87, 164));
        jLabel6.setText("WELCOME");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(72, 87, 164));
        jLabel7.setText("Doctor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 150, 40));

        jButton3.setBackground(new java.awt.Color(242, 242, 242));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-01-01 011758_1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 770, 110, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1920x1080-white-solid-color-background.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String diagnosisId = jTextField2.getText().trim();  // Get Diagnosis ID
    String patientName = jTextField1.getText().trim();   // Get Patient Name
    String diagnosisName = jTextField3.getText().trim(); // Get Diagnosis Name

    // Check if any field is empty
    if (diagnosisId.isEmpty() || patientName.isEmpty() || diagnosisName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields before adding a diagnosis.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate that Diagnosis ID contains only numeric digits
    if (!diagnosisId.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Diagnosis ID must contain only numeric digits.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

 String url = "jdbc:postgresql://localhost:5432/postgres";
String user = "dentalclinic";
String password = "12345";

    // SQL query to insert a new diagnosis record
    String query = "INSERT INTO public.diagnosis (did, pname, dtype) VALUES (?, ?, ?)";

    try (
        // Establish connection to the database
        Connection con = DriverManager.getConnection(url, user, password);
        // Prepare the SQL statement
        PreparedStatement pst = con.prepareStatement(query)
    ) {
        // Set the parameters in the PreparedStatement
        pst.setInt(1, Integer.parseInt(diagnosisId));  // Set the Diagnosis ID as integer
        pst.setString(2, patientName);                  // Set the Patient Name
        pst.setString(3, diagnosisName);                // Set the Diagnosis Name

        // Execute the insert query
        int rowsInserted = pst.executeUpdate();

        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Diagnosis added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Optionally, refresh the table to display the newly added record
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);  // Clear the table before adding new data

            // Add code to fetch the data again and display the updated table
            // Example: fetchDiagnosisData();

        } else {
            JOptionPane.showMessageDialog(this, "Failed to add diagnosis.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        // Handle invalid Diagnosis ID input
        JOptionPane.showMessageDialog(this, "Diagnosis ID must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        // Log and display database errors
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error while adding diagnosis: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    
    
    
    
    
    
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
String inputPid = jTextField2.getText().trim(); // Input field for Patient ID
String inputPname = jTextField1.getText().trim(); // Input field for Patient Name

// Validate the input fields
if (inputPid.isEmpty() || inputPname.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all fields to search.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

int dId = -1;
try {
    // Validate that treatmentId is a valid integer
    dId = Integer.parseInt(inputPid);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Treatment ID must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

String url = "jdbc:postgresql://localhost:5432/postgres";
String user = "dentalclinic";
String password = "12345";

// SQL query to search for records based on the input values
String query = "SELECT * FROM public.diagnosis WHERE did = ? AND pname = ?";

try (
    // Establish connection to the database
    Connection con = DriverManager.getConnection(url, user, password);
    // Prepare the SQL statement
    PreparedStatement pst = con.prepareStatement(query)
) {
    // Set the parameters for the SQL query
    pst.setInt(1, dId); // Set treatment_id
    pst.setString(2, inputPname); // Set patient_name

    // Execute the query
    ResultSet rs = pst.executeQuery();

    // Check if results are found
    if (rs.next()) {
        // Assuming your JTable model is already set up with appropriate column headers
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 

        // Clear any existing rows in the table
        model.setRowCount(0);

        // Get the number of columns in the result set
        int columnCount = rs.getMetaData().getColumnCount();

        // Add retrieved record(s) to the table
        do {
            // Create an Object array to hold the data for each row
            Object[] row = new Object[columnCount];

            // Loop through all the columns for the current row
            for (int i = 1; i <= columnCount; i++) {
                row[i - 1] = rs.getObject(i);  // Get each column value and add it to the row array
            }

            model.addRow(row);  // Add the row to the table model
        } while (rs.next());

    } else {
        JOptionPane.showMessageDialog(this, "No record found matching the search criteria.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }

} catch (SQLException e) {
    // Log and display database errors
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error while searching: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    // Catch any other unexpected exceptions
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
String diagnosisId = jTextField2.getText().trim();  // Treat diagnosisId as a String
    String patientName = jTextField1.getText().trim();  // Get Patient Name
    String diagnosisName = jTextField3.getText().trim();  // Get Diagnosis Name

    // Check if Patient Name or Diagnosis Name is empty
    if (patientName.isEmpty() || diagnosisName.isEmpty() || diagnosisId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields before updating.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate that Diagnosis ID is numeric
    if (!diagnosisId.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Diagnosis ID must contain only numeric digits.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

     String url = "jdbc:postgresql://localhost:5432/postgres";
    String user = "dentalclinic";
    String password ="12345" ;
    
   
    String query = "UPDATE public.diagnosis SET pname = ?, dtype = ? WHERE did = ?";

    try (
        // Establish connection to the database
        Connection con = DriverManager.getConnection(url, user, password);
        // Prepare the SQL statement
        PreparedStatement pst = con.prepareStatement(query)
    ) {
        // Set parameters in the PreparedStatement
        pst.setString(1, patientName);   // Set patient name
        pst.setString(2, diagnosisName); // Set diagnosis name
        pst.setInt(3, Integer.parseInt(diagnosisId));   // Set diagnosisId as integer

        // Execute the query to update the diagnosis
        int rowsUpdated = pst.executeUpdate();

        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(this, "Diagnosis updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Optionally, refresh the table
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Clear the table before fetching new data
            // Add code to fetch the updated table and display it (similar to how you did before)

        } else {
            JOptionPane.showMessageDialog(this, "No record found to update.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (NumberFormatException e) {
        // Handle invalid Diagnosis ID input
        JOptionPane.showMessageDialog(this, "Diagnosis ID must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        // Log and display database errors
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error while updating: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        String url = "jdbc:postgresql://localhost:5432/postgres";
        String user = "dentalclinic";
        String password = "12345";

        String sql = "SELECT * FROM public.diagnosis";

        try (Connection conn = DriverManager.getConnection(url, user, password);
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                int diagnosisId = rs.getInt("did");
                String diagnosisName = rs.getString("dtype");
                String patientName = rs.getString("pname");

                model.addRow(new Object[]{diagnosisId, patientName, diagnosisName});
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      String diagnosisId = jTextField2.getText().trim(); // Assume jTextField2 holds the Diagnosis ID

    // Check if the Diagnosis ID is empty
    if (diagnosisId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a Diagnosis ID to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate that Diagnosis ID contains only numeric digits
    if (!diagnosisId.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Diagnosis ID must contain only numeric digits.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

     String url = "jdbc:postgresql://localhost:5432/postgres";
    String user = "dentalclinic";
    String password ="12345" ;

    // SQL query to delete a diagnosis record based on Diagnosis ID
    String query = "DELETE FROM public.diagnosis WHERE did = ?";

    try (
        // Establish connection to the database
        Connection con = DriverManager.getConnection(url, user, password);
        // Prepare the SQL statement
        PreparedStatement pst = con.prepareStatement(query)
    ) {
        // Set the Diagnosis ID in the PreparedStatement
        pst.setInt(1, Integer.parseInt(diagnosisId));  // Set the Diagnosis ID as integer

        // Execute the delete query
        int rowsDeleted = pst.executeUpdate();

        if (rowsDeleted > 0) {
            JOptionPane.showMessageDialog(this, "Diagnosis deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Optionally, refresh the table to reflect the changes
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);  // Clear the table before adding new data

            // Add code to fetch and display the updated table (like you did before)
            // Example: fetchDiagnosisData();

        } else {
            JOptionPane.showMessageDialog(this, "No diagnosis found with the given ID to delete.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (NumberFormatException e) {
        // Handle invalid Diagnosis ID input
        JOptionPane.showMessageDialog(this, "Diagnosis ID must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        // Log and display database errors
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error while deleting: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        patient patientUI = new patient();
        patientUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        treatment treatmentUI = new treatment();
        treatmentUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        appointment1 appointment1UI = new appointment1();
        appointment1UI.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        medication pres_medicationUI = new medication();
        pres_medicationUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        dianosis1 diagnosisUI = new dianosis1();
        diagnosisUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        wlecomepage lb=new wlecomepage();
        lb.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dianosis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dianosis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dianosis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dianosis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dianosis1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
