/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clinicemail.sendmail;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author farah
 */
public class resetpage extends javax.swing.JFrame {

    Connection con=null;
           ResultSet rs=null;
           PreparedStatement pst=null;
         
           
    public resetpage() {
        initComponents();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resetb = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        name = new javax.swing.JTextField();
        Vpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resetb.setBackground(new java.awt.Color(242, 242, 242));
        resetb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resetb.setForeground(new java.awt.Color(72, 87, 164));
        resetb.setText("Reset");
        resetb.setBorder(null);
        resetb.setBorderPainted(false);
        resetb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resetb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbActionPerformed(evt);
            }
        });
        getContentPane().add(resetb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 160, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 31)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Verify password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 290, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 31)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 270, 40));

        password.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 390, 60));

        name.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 390, 60));

        Vpassword.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Vpassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        getContentPane().add(Vpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 390, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 31)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ezgif-2-6ff5192e61.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 480, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbActionPerformed
if (!(new String(password.getPassword()).equals(new String(Vpassword.getPassword())))) {
    JOptionPane.showMessageDialog(null, "Your Password Does Not Match!!");
} else {
    try {
        // Queries for both databases
        String updateQueryLogin = "UPDATE login.login_cre SET userpassword = ? WHERE username = ?";
        String updateQueryDoctors = "UPDATE login.\"loginDoctors\" SET userpassword = ? WHERE username = ?";

        // Establish connections to both databases
        Connection connLogin = DriverManager.getConnection(
                "jdbc:postgresql://localhost:5432/Userlogin", "dentalclinic", "12345");
        Connection connDoctors = DriverManager.getConnection(
                "jdbc:postgresql://localhost:5432/Userlogin", "dentalclinic", "12345");

        // Update login database
        PreparedStatement pstLogin = connLogin.prepareStatement(updateQueryLogin);
        pstLogin.setString(1, new String(password.getPassword())); // New password
        pstLogin.setString(2, name.getText()); // Username
        int rowsUpdatedLogin = pstLogin.executeUpdate();

        // Update loginDoctors database
        PreparedStatement pstDoctors = connDoctors.prepareStatement(updateQueryDoctors);
        pstDoctors.setString(1, new String(password.getPassword())); // New password
        pstDoctors.setString(2, name.getText()); // Username
        int rowsUpdatedDoctors = pstDoctors.executeUpdate();

        // Check the results
        if (rowsUpdatedLogin > 0 || rowsUpdatedDoctors > 0) {
            JOptionPane.showMessageDialog(null, "Reset Successfully");
            wlecomepage lb = new wlecomepage();
            lb.show();
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Username not found in both databases!");
        }

        // Close connections
        pstLogin.close();
        connLogin.close();
        pstDoctors.close();
        connDoctors.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
}

       
    }//GEN-LAST:event_resetbActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Vpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton resetb;
    // End of variables declaration//GEN-END:variables
}
