/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clinicemail.sendmail;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author farah
 */
public class TreatmentAssistant extends javax.swing.JFrame {

    /**
     * Creates new form TreatmentAssistant
     */
    public TreatmentAssistant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Cose = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(72, 87, 164));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(72, 87, 164));
        jLabel1.setText("WELCOME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, -1));

        jButton3.setBackground(new java.awt.Color(242, 242, 242));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(72, 87, 164));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 191209 (1).gif"))); // NOI18N
        jButton3.setText("Appointment ");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 320, 110));

        jButton4.setBackground(new java.awt.Color(242, 242, 242));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(72, 87, 164));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 191921.gif"))); // NOI18N
        jButton4.setText("  Treatment");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 320, 110));

        Cose.setBackground(new java.awt.Color(242, 242, 242));
        Cose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Cose.setForeground(new java.awt.Color(72, 87, 164));
        Cose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-04 185610.gif"))); // NOI18N
        Cose.setText("Cost");
        Cose.setBorder(null);
        Cose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoseActionPerformed(evt);
            }
        });
        getContentPane().add(Cose, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 320, 110));

        jButton2.setBackground(new java.awt.Color(242, 242, 242));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(72, 87, 164));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 191732 (1).gif"))); // NOI18N
        jButton2.setText("  Patient ");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 320, 110));

        jButton9.setBackground(new java.awt.Color(242, 242, 242));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(72, 87, 164));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screen Recording 2025-01-03 192236 (1).gif"))); // NOI18N
        jButton9.setText("Dentists");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 320, 120));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(72, 87, 164));
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 100, 270, 37));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(72, 87, 164));
        jLabel3.setText("treatment type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 190, -1, 37));

        jButton5.setBackground(new java.awt.Color(242, 242, 242));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(72, 87, 164));
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 350, 190, 60));

        jButton7.setBackground(new java.awt.Color(242, 242, 242));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(72, 87, 164));
        jButton7.setText("Show");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 270, 190, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(72, 87, 164));
        jLabel4.setText("Assistant");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 150, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Treatment_id", "Treatment_type", "Treatment_Cost", "pname"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 750, 300));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(72, 87, 164));
        jLabel5.setText("Cost");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 100, -1, 37));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(72, 87, 164));
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 270, 37));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(72, 87, 164));
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 190, 270, 37));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(72, 87, 164));
        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 270, 37));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(72, 87, 164));
        jLabel6.setText("Patiant Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, 37));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(72, 87, 164));
        jLabel7.setText("id");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 150, 37));

        jButton6.setBackground(new java.awt.Color(242, 242, 242));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(72, 87, 164));
        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 430, 190, 60));

        jButton8.setBackground(new java.awt.Color(242, 242, 242));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(72, 87, 164));
        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 510, 190, 60));

        jButton10.setBackground(new java.awt.Color(242, 242, 242));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(72, 87, 164));
        jButton10.setText("Delete");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 590, 190, 60));

        jButton11.setBackground(new java.awt.Color(242, 242, 242));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-01-01 011758_1.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 770, 110, 80));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(72, 87, 164));
        jLabel8.setText("treatment id");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 150, 37));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(72, 87, 164));
        jTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 87, 164), 1, true));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 270, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1920x1080-white-solid-color-background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1550, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          AppointmentAssistant appointment = new AppointmentAssistant();
        appointment.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       TreatmentAssistant treatment = new TreatmentAssistant();
        treatment.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoseActionPerformed
     CostDetails CostDetails1 = new CostDetails();
        CostDetails1.setVisible(true);
        dispose();
    }//GEN-LAST:event_CoseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        assistantP patient = new assistantP();
        patient.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
          Dentists diagnosis = new Dentists();
        diagnosis.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    // Retrieve the patient's name from the text field
    String patientName = jTextField5.getText();

    // Check if the patient name is empty
    if (patientName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a patient name to search.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Define the query to search for treatments based on the patient name
    String query = "SELECT * FROM public.treatment WHERE pname = ?";

    // Database connection details
    String url = "jdbc:postgresql://localhost:5432/postgres";  // Replace with your database URL
    String username = "dentalclinic";  // Replace with your database username
    String password = "12345";  // Replace with your database password
    // Establish connection with the database
    try (Connection con = DriverManager.getConnection(url, username, password);
            PreparedStatement pst = con.prepareStatement(query)) {
        
        // Set the patient name parameter in the query
        pst.setString(1, patientName);
        
        // Execute the query and retrieve the result set
        ResultSet rs = pst.executeQuery();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        // Clear the table model before adding new data
        model.setRowCount(0);
        
        // Iterate through the result set and populate the table
        while (rs.next()) {
            
             int tId = rs.getInt("t_id");
                int treatmentId = rs.getInt("treatment_id");
                String treatmentType = rs.getString("ttype");
                String treatmentcost = rs.getString("treatment_cost_paid_amount");
                String pname = rs.getString("pname");

                model.addRow(new Object[]{tId,treatmentId, treatmentType, treatmentcost,pname});
        }
        
        // If no rows are returned, show a message
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No treatments found for the given patient name.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        
    } catch (SQLException e) {
        // Handle SQL exceptions
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error while searching: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        String url = "jdbc:postgresql://localhost:5432/postgres";
        String user = "dentalclinic";
        String password = "12345";

        String sql = "SELECT * FROM public.treatment";

        try (Connection conn = DriverManager.getConnection(url, user, password);
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                int tId = rs.getInt("t_id");
                int treatmentId = rs.getInt("treatment_id");
                String treatmentType = rs.getString("ttype");
                String treatmentcost = rs.getString("treatment_cost_paid_amount");
                String pname = rs.getString("pname");

                model.addRow(new Object[]{tId,treatmentId, treatmentType, treatmentcost,pname});

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
String tid = jTextField3.getText().trim(); // Treatment ID field
String patientName = jTextField5.getText().trim(); // Patient Name field
String cost = jTextField2.getText().trim(); // Treatment cost field
String Ttype = jTextField4.getText().trim(); // Treatment type field

// Validate the input fields
if (tid.isEmpty() || patientName.isEmpty() || cost.isEmpty() || Ttype.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all fields before adding.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Convert the treatment cost from String to double
double treatmentCost = -1;
try {
    treatmentCost = Double.parseDouble(cost); // Convert the cost to double
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Treatment cost must be a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
    return; // Exit if the cost is not a valid number
}

int tId = -1;
try {
    // Validate that treatmentId is a valid integer
    tId = Integer.parseInt(tid);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Treatment ID must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

String url = "jdbc:postgresql://localhost:5432/postgres";
String user = "dentalclinic";
String password = "12345";

// Correct SQL query to insert the new treatment information
String query = "INSERT INTO public.treatment (treatment_id, ttype, treatment_cost_paid_amount, pname) VALUES (?, ?, ?, ?)";

try (
    // Establish connection to the database
    Connection con = DriverManager.getConnection(url, user, password);
    // Prepare the SQL statement
    PreparedStatement pst = con.prepareStatement(query)
) {
    // Set the parameters for the SQL query
    pst.setInt(1, tId);               // Set treatment_id (TID) as integer
    pst.setString(2, Ttype);           // Set treatment type (Ttype)
    pst.setDouble(3, treatmentCost);   // Set treatment cost (treatment_cost_paid_amount) as double
    pst.setString(4, patientName);     // Set patient name (pname)

    // Execute the insert query
    int rowsInserted = pst.executeUpdate();

    if (rowsInserted > 0) {
        JOptionPane.showMessageDialog(this, "Treatment added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Optionally, refresh the table to reflect the changes (if you have a table to display treatment info)
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();  // Assuming 'jTable2' is your JTable
        model.setRowCount(0);  // Clear the table before adding new data

        // Optionally, fetch and display the updated data here
        // Example: fetchTreatmentData();
    } else {
        JOptionPane.showMessageDialog(this, "Error adding the treatment.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }

} catch (SQLException e) {
    // Log and display database errors
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error while adding treatment: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    // Catch any other unexpected exceptions
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
String tid = jTextField6.getText().trim();
String treatmentid = jTextField3.getText().trim();
String patientName = jTextField5.getText().trim();
String cost = jTextField2.getText().trim();
String Ttype = jTextField4.getText().trim();

if (tid.isEmpty() || treatmentid.isEmpty() || patientName.isEmpty() || cost.isEmpty() || Ttype.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all fields before updating.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

double treatmentCost = -1;
try {
    treatmentCost = Double.parseDouble(cost);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Treatment cost must be a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

int tId = -1;
int treatmentId = -1;

try {
    tId = Integer.parseInt(tid);
    treatmentId = Integer.parseInt(treatmentid);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Treatment ID and Patient ID must be valid integers.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

String url = "jdbc:postgresql://localhost:5432/postgres";
String user = "dentalclinic";
String password = "12345";

String query = "UPDATE public.treatment SET treatment_id = ?, ttype = ?, treatment_cost_paid_amount = ?, pname = ? WHERE t_id = ?";

try (
    Connection con = DriverManager.getConnection(url, user, password);
    PreparedStatement pst = con.prepareStatement(query)
) {
    pst.setInt(1, treatmentId); // Set treatment_id
    pst.setString(2, Ttype); // Set treatment type (Ttype)
    pst.setDouble(3, treatmentCost); // Set treatment cost (treatment_cost_paid_amount)
    pst.setString(4, patientName); // Set patient name (pname)
    pst.setInt(5, tId); // Set treatment_id (TID) for the WHERE clause

    int rowsUpdated = pst.executeUpdate();

    if (rowsUpdated > 0) {
        JOptionPane.showMessageDialog(this, "Treatment updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
    } else {
        JOptionPane.showMessageDialog(this, "No treatment found with the specified ID.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }

} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error while updating treatment: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
String tid = jTextField3.getText().trim();
String pname = jTextField5.getText().trim();

if (tid.isEmpty() || pname.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please provide both Treatment ID and Patient Name to delete.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

int tId = -1;
try {
    tId = Integer.parseInt(tid);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Treatment ID must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

String url = "jdbc:postgresql://localhost:5432/postgres";
String user = "dentalclinic";
String password = "12345";

String query = "DELETE FROM public.treatment WHERE treatment_id = ? AND pname = ?";

try (
    Connection con = DriverManager.getConnection(url, user, password);
    PreparedStatement pst = con.prepareStatement(query)
) {
    pst.setInt(1, tId);
    pst.setString(2, pname);

    int rowsDeleted = pst.executeUpdate();

    if (rowsDeleted > 0) {
        JOptionPane.showMessageDialog(this, "Treatment deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
    } else {
        JOptionPane.showMessageDialog(this, "No treatment found with the specified Treatment ID and Patient Name.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }

} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error while deleting treatment: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}


       

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        wlecomepage lb=new wlecomepage();
        lb.show();
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreatmentAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreatmentAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreatmentAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreatmentAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreatmentAssistant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cose;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
